import type { ImageStyle, TextStyle, ViewStyle } from 'react-native';

import type { ComponentTheme } from '@/theme/types/theme';

type AllStyle = {} & Record<string, ImageStyle | TextStyle | ViewStyle>;

const generateComponentStyles = ({
  backgrounds,
  borders,
  colors,
  fonts,
  layout,
  variant,
}: ComponentTheme) => {
  return {
    badge: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...layout.absolute,
      backgroundColor: colors.red500,
      borderRadius: 9,
      height: 18,
      minWidth: 18,
      paddingHorizontal: 4,
      right: -6,
      top: -6,
    },
    badgeLabel: {
      ...fonts.bold,
      color: '#FFFFFF',
      fontSize: 10,
    },
    buttonCircle: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...backgrounds.purple100,
      ...fonts.gray400,
      borderRadius: 35,
      height: 64,
      width: 64,
    },
    buttonPill: {
      ...layout.row,
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      backgroundColor: colors.blue500,
      borderRadius: 26,
      gap: 8,
      height: 52,
      paddingHorizontal: 24,
    },
    buttonPillLabel: {
      ...fonts.bold,
      color: '#FFFFFF',
      fontSize: 16,
    },
    buttonPrimary: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_16,
      backgroundColor: colors.purple500,
      height: 56,
    },
    buttonPrimaryDisabled: {
      opacity: 0.5,
    },
    buttonPrimaryLabel: {
      ...fonts.bold,
      color: variant === 'dark' ? colors.purple50 : colors.gray50,
      fontSize: 16,
    },
    card: {
      ...borders.rounded_16,
      ...borders.w_1,
      backgroundColor: colors.surface,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      padding: 16,
    },
    cardTitle: {
      ...fonts.bold,
      color: colors.gray800,
      fontSize: 16,
    },
    categoryChip: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_20,
      ...borders.w_1,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      height: 40,
      paddingHorizontal: 16,
    },
    categoryChipActive: {
      backgroundColor: colors.blue500,
      borderColor: colors.blue500,
    },
    categoryChipLabel: {
      color: colors.gray400,
      fontSize: 14,
    },
    categoryChipLabelActive: {
      ...fonts.bold,
      color: '#FFFFFF',
    },
    circle250: {
      borderRadius: 140,
      height: 250,
      width: 250,
    },
    dateChip: {
      ...layout.row,
      ...layout.itemsCenter,
      ...borders.rounded_12,
      ...borders.w_1,
      backgroundColor: colors.surface,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      gap: 6,
      height: 44,
      paddingHorizontal: 12,
    },
    iconButtonSquare: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_12,
      ...borders.w_1,
      backgroundColor: colors.surface,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      height: 44,
      width: 44,
    },
    quickAction: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_12,
      ...borders.w_1,
      backgroundColor: colors.surface,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      flex: 1,
      gap: 6,
      paddingHorizontal: 4,
      paddingVertical: 12,
    },
    quickActionIcon: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_8,
      height: 36,
      width: 36,
    },
    searchInput: {
      ...layout.flex_1,
      color: colors.gray800,
      fontSize: 14,
      padding: 0,
    },
    searchInputWrapper: {
      ...layout.row,
      ...layout.itemsCenter,
      ...borders.rounded_12,
      ...borders.w_1,
      backgroundColor: colors.surfaceSunken,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      gap: 8,
      height: 44,
      paddingHorizontal: 12,
    },
    segmentTab: {
      ...layout.itemsCenter,
      flex: 1,
      paddingBottom: 10,
    },
    segmentTabIndicator: {
      borderRadius: 2,
      height: 2,
      marginTop: 10,
      width: '100%',
    },
    severityTile: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_8,
      ...borders.w_1,
      height: 44,
      width: 44,
    },
    statTile: {
      ...borders.rounded_16,
      ...borders.w_1,
      gap: 4,
      padding: 12,
      width: 140,
    },
    statusPill: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_8,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    statusPillLabel: {
      fontSize: 12,
    },
    statValue: {
      ...fonts.bold,
      color: colors.gray800,
      fontSize: 20,
    },
    summaryStrip: {
      ...layout.row,
      ...borders.rounded_16,
      ...borders.w_1,
      backgroundColor: colors.surface,
      borderColor: variant === 'dark' ? colors.purple100 : colors.gray100,
      paddingVertical: 12,
    },
    summaryValue: {
      ...fonts.bold,
      fontSize: 20,
    },
    summaryValueLarge: {
      ...fonts.bold,
      fontSize: 22,
    },
    tabBarFab: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      backgroundColor: colors.blue500,
      borderRadius: 28,
      elevation: 6,
      height: 56,
      shadowColor: '#000000',
      shadowOffset: { height: 4, width: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      width: 56,
    },
    tabBarSurface: {
      ...layout.row,
      ...borders.wTop_1,
      backgroundColor: colors.surface,
      borderTopColor: variant === 'dark' ? colors.purple100 : colors.gray100,
    },
    tabCountBadge: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      borderRadius: 10,
      height: 20,
      minWidth: 20,
      paddingHorizontal: 6,
    },
    tabCountLabel: {
      ...fonts.bold,
      fontSize: 11,
    },
    tagChip: {
      ...layout.justifyCenter,
      ...layout.itemsCenter,
      ...borders.rounded_4,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    tagChipLabel: {
      fontSize: 10,
    },
    textInput: {
      ...borders.rounded_16,
      ...borders.w_1,
      ...backgrounds.purple100,
      borderColor: colors.purple100,
      color: colors.gray800,
      fontSize: 16,
      height: 56,
      paddingHorizontal: 16,
    },
    textInputError: {
      borderColor: colors.red500,
    },
    textInputFocused: {
      borderColor: colors.purple500,
    },
  } as const satisfies AllStyle;
};

export default generateComponentStyles;
