export const enum Paths {
  AddIngredient = 'addIngredient',
  Alerts = 'alerts',
  ChangePassword = 'changePassword',
  CreateDocument = 'createDocument',
  Example = 'example',
  Ingredients = 'ingredients',
  ItemDetail = 'itemDetail',
  Login = 'login',
  MainTabs = 'mainTabs',
  More = 'more',
  Overview = 'overview',
  PrepTasks = 'prepTasks',
  PurchaseGuide = 'purchaseGuide',
  ReceiptDetail = 'receiptDetail',
  SauceDetail = 'sauceDetail',
  Sauces = 'sauces',
  Startup = 'startup',
  TransactionHistory = 'transactionHistory',
  Transactions = 'transactions',
}
